AWSTemplateFormatVersion: "2010-09-09"

Resources:
  PrescribingProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for prescribing proxygen
      KmsKeyId: !ImportValue secrets-cdk:KMS:SecretsKMSKeyAlias:Arn
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Prescribing-ProxygenPrivateKey"

  PrescribingProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for prescribing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Prescribing-ProxygenPublicKey"

  PrescribingProxygenKid:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: kid for prescribing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Prescribing-ProxygenKid"

  PrescribingProxygenProdPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for prescribing proxygen prod
      KmsKeyId: !ImportValue secrets-cdk:KMS:SecretsKMSKeyAlias:Arn
      SecretString: ChangeMe
      Name: "FhirPrescribingProxygen-PrivateKey-prod"

  PrescribingProxygenProdPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for prescribing proxygen prod
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "FhirPrescribingProxygen-PublicKey-prod"

  PrescribingProxygenProdKid:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: kid for prescribing proxygen prod
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "FhirPrescribingProxygen-kid-prod"

  PrescribingProxygenPtlPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for prescribing proxygen ptl
      KmsKeyId: !ImportValue secrets-cdk:KMS:SecretsKMSKeyAlias:Arn
      SecretString: ChangeMe
      Name: "FhirPrescribingProxygen-PrivateKey-ptl"

  PrescribingProxygenPtlPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for prescribing proxygen ptl
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "FhirPrescribingProxygen-PublicKey-ptl"

  PrescribingProxygenPtlKid:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: KID for prescribing proxygen ptl
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "FhirPrescribingProxygen-kid-ptl"

  DispensingProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for dispensing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Dispensing-ProxygenPrivateKey"

  DispensingProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for dispensing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Dispensing-ProxygenPublicKey"

  DispensingProxygenKid:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Kid for dispensing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Dispensing-ProxygenKid"

  DispensingProxygenProdPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for dispensing proxygen prod
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "FhirDispensingProxygen-PrivateKey-prod"

  DispensingProxygenProdPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for dispensing proxygen prod
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "FhirDispensingProxygen-PublicKey-prod"
  DispensingProxygenProdKid:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Kid for dispensing proxygen prod
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "FhirDispensingProxygen-kid-prod"

  DispensingProxygenPtlPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for dispensing proxygen ptl
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "FhirDispensingProxygen-PrivateKey-ptl"

  DispensingProxygenPtlPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for dispensing proxygen ptl
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "FhirDispensingProxygen-PublicKey-ptl"

  DispensingProxygenPtlKid:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: KID for dispensing proxygen ptl
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "FhirDispensingProxygen-kid-ptl"

  PrescriptionsForPatientsProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for PrescriptionsForPatients proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PrescriptionsForPatients-ProxygenPrivateKey"

  PrescriptionsForPatientsProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for PrescriptionsForPatients proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PrescriptionsForPatients-ProxygenPublicKey"

  PrescriptionsForPatientsProxygenKid:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Kid for PrescriptionsForPatients proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PrescriptionsForPatients-ProxygenKid"

  PrescriptionsForPatientsProxygenProdPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for PrescriptionsForPatients proxygen prod
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "PrescriptionsForPatientsProxygen-PrivateKey-prod"

  PrescriptionsForPatientsProxygenProdPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for PrescriptionsForPatients proxygen prod
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "PrescriptionsForPatientsProxygen-PublicKey-prod"
  PrescriptionsForPatientsProxygenProdKid:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: kid for PrescriptionsForPatients proxygen prod
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "PrescriptionsForPatientsProxygen-kid-prod"


  PrescriptionsForPatientsProxygenPtlPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for PrescriptionsForPatients proxygen ptl
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "PrescriptionsForPatientsProxygen-PrivateKey-ptl"

  PrescriptionsForPatientsProxygenPtlPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for PrescriptionsForPatients proxygen ptl
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "PrescriptionsForPatientsProxygen-PublicKey-ptl"

  PrescriptionsForPatientsProxygenPtlKid:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: kid for PrescriptionsForPatients proxygen ptl
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: "PrescriptionsForPatientsProxygen-kid-ptl"

  epsSigningCertChain:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Cert chain used for signing prescriptions. Used to validate prescriptions are valid
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-epsSigningCertChain"

  epsSigningCertChainManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !GetAtt epsSigningCertChain.Id

  ptlPrescriptionSigningPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key used to sign prescriptions in PTL environments
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-ptlPrescriptionSigningPrivateKey"

  ptlPrescriptionSigningPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key used to sign prescriptions in PTL environments
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-ptlPrescriptionSigningPublicKey"

  #endregion

Outputs:
  PrescribingProxygenPrivateKey:
    Description: PrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescribingProxygenPrivateKey"]]

  PrescribingProxygenPublicKey:
    Description: PrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescribingProxygenPublicKey"]]

  DispensingProxygenPrivateKey:
    Description: PrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DispensingProxygenPrivateKey"]]

  DispensingProxygenPublicKey:
    Description: PrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DispensingProxygenPublicKey"]]

  FhirPrescribingProxygenPrivateKey:
    Description: FhirPrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirPrescribingProxygenPrivateKey"]]

  FhirPrescribingProxygenPublicKey:
    Description: FhirPrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirPrescribingProxygenPublicKey"]]

  FhirPrescribingProxygenKid:
    Description: FhirPrescribingProxygenKid
    Value: !GetAtt PrescribingProxygenKid.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirPrescribingProxygenKid"]]

  FhirDispensingProxygenPrivateKey:
    Description: FhirDispensingProxygenPrivateKey
    Value: !GetAtt DispensingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirDispensingProxygenPrivateKey"]]

  FhirDispensingProxygenPublicKey:
    Description: FhirDispensingProxygenPublicKey
    Value: !GetAtt DispensingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirDispensingProxygenPublicKey"]]

  FhirDispensingProxygenKid:
    Description: FhirDispensingProxygenKid
    Value: !GetAtt DispensingProxygenKid.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirDispensingProxygenKid"]]

  PrescriptionsForPatientsProxygenPrivateKey:
    Description: PrescriptionsForPatientsProxygenPrivateKey
    Value: !GetAtt PrescriptionsForPatientsProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescriptionsForPatientsProxygenPrivateKey"]]

  PrescriptionsForPatientsProxygenPublicKey:
    Description: PrescriptionsForPatientsProxygenPublicKey
    Value: !GetAtt PrescriptionsForPatientsProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescriptionsForPatientsProxygenPublicKey"]]

  PrescriptionsForPatientsProxygenKid:
    Description: PrescriptionsForPatientsProxygenKid
    Value: !GetAtt PrescriptionsForPatientsProxygenKid.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescriptionsForPatientsProxygenKid"]]

  epsSigningCertChain:
    Description: epsSigningCertChain
    Value: !GetAtt epsSigningCertChain.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "epsSigningCertChain"]]

  epsSigningCertChainManagedPolicy:
    Description: epsSigningCertChainManagedPolicy
    Value: !GetAtt epsSigningCertChainManagedPolicy.PolicyArn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "epsSigningCertChainManagedPolicy"]]

  ptlPrescriptionSigningPublicKey:
    Description: ptlPrescriptionSigningPublicKey
    Value: !GetAtt ptlPrescriptionSigningPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "ptlPrescriptionSigningPublicKey"]]

  ptlPrescriptionSigningPrivateKey:
    Description: ptlPrescriptionSigningPrivateKey
    Value: !GetAtt ptlPrescriptionSigningPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "ptlPrescriptionSigningPrivateKey"]]

  PrescribingProxygenProdPrivateKey:
    Description: PrescribingProxygenProdPrivateKey
    Value: !GetAtt PrescribingProxygenProdPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescribingProxygenProdPrivateKey"]]

  PrescribingProxygenProdKid:
    Description: PrescribingProxygenProdKid
    Value: !GetAtt PrescribingProxygenProdKid.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescribingProxygenProdKid"]]

  PrescribingProxygenPtlPrivateKey:
    Description: PrescribingProxygenPtlPrivateKey
    Value: !GetAtt PrescribingProxygenPtlPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescribingProxygenPtlPrivateKey"]]

  PrescribingProxygenPtlKid:
    Description: PrescribingProxygenPtlKid
    Value: !GetAtt PrescribingProxygenPtlKid.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescribingProxygenPtlKid"]]

  DispensingProxygenProdPrivateKey:
    Description: DispensingProxygenProdPrivateKey
    Value: !GetAtt DispensingProxygenProdPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DispensingProxygenProdPrivateKey"]]
  DispensingProxygenProdKid:
    Description: DispensingProxygenProdKid
    Value: !GetAtt DispensingProxygenProdKid.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DispensingProxygenProdKid"]]
  DispensingProxygenPtlPrivateKey:
    Description: DispensingProxygenPtlPrivateKey
    Value: !GetAtt DispensingProxygenPtlPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DispensingProxygenPtlPrivateKey"]]
  DispensingProxygenPtlKid:
    Description: DispensingProxygenPtlKid
    Value: !GetAtt DispensingProxygenPtlKid.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DispensingProxygenPtlKid"]]
  PrescriptionsForPatientsProxygenProdPrivateKey:
    Description: PrescriptionsForPatientsProxygenProdPrivateKey
    Value: !GetAtt PrescriptionsForPatientsProxygenProdPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescriptionsForPatientsProxygenProdPrivateKey"]]
  PrescriptionsForPatientsProxygenProdKid:
    Description: PrescriptionsForPatientsProxygenProdKid
    Value: !GetAtt PrescriptionsForPatientsProxygenProdKid.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescriptionsForPatientsProxygenProdKid"]]
  PrescriptionsForPatientsProxygenPtlPrivateKey:
    Description: PrescriptionsForPatientsProxygenPtlPrivateKey
    Value: !GetAtt PrescriptionsForPatientsProxygenPtlPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescriptionsForPatientsProxygenPtlPrivateKey"]]
  PrescriptionsForPatientsProxygenPtlKid:
    Description: PrescriptionsForPatientsProxygenPtlKid
    Value: !GetAtt PrescriptionsForPatientsProxygenPtlKid.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescriptionsForPatientsProxygenPtlKid"]]
