name: deploy to environments

on:
  workflow_dispatch:

permissions: {}

jobs:
  get_config_values:
    uses: NHSDigital/eps-common-workflows/.github/workflows/get-repo-config.yml@889349f9d93e4846a642f7973b7c26b180bec5aa
    permissions:
      attestations: read
      contents: read
      packages: read
    with:
      verify_published_from_main_image: true
  
  quality_checks:
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks-devcontainer.yml@889349f9d93e4846a642f7973b7c26b180bec5aa
    needs: [get_config_values]
    permissions:
      contents: read
      id-token: write
      packages: read
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  package_code:
    uses: ./.github/workflows/sam_package_code.yml
    needs: get_config_values
    permissions:
      contents: read
      id-token: write
      packages: read
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}

  package_cdk_code:
    uses: ./.github/workflows/cdk_package_code.yml
    needs: get_config_values
    permissions:
      contents: read
      id-token: write
      packages: read
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}

  get_commit_id:
    runs-on: ubuntu-22.04
    outputs:
      commit_id: ${{ steps.commit_id.outputs.commit_id }}
    steps:
      - name: Get Commit ID
        id: commit_id
        run: |
          echo "commit_id=${{ github.sha }}" >> "$GITHUB_OUTPUT"
  
  tag_release:
    needs: [quality_checks, package_code, package_cdk_code, get_commit_id, get_config_values]
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release-devcontainer.yml@bda627e2ce1a32ea56bcc815aec57b06cfa63c9d
    permissions:
      id-token: write
      contents: write
      packages: write
    with:
      dry_run: false
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      branch_name: main
      tag_format: ${{ needs.get_config_values.outputs.tag_format }}
      update_jira: true
      jira_release_prefix: "account-resources"
    secrets:
      EXECUTE_JIRA_LAMBDA_ROLE: ${{ secrets.DEV_CLOUD_FORMATION_EXECUTE_LAMBDA_ROLE }}
  
  deploy_dev_stacks:
    needs: [get_commit_id, package_code, package_cdk_code, tag_release, get_config_values]
    uses: ./.github/workflows/release_all_stacks.yml
    permissions:
      id-token: write
      contents: write
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      target_environment: dev
      version: ${{ needs.tag_release.outputs.version_tag }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      execute_change_set: true
      lambda_stack_suffix: ""
      artifact_bucket_prefix: ${{needs.tag_release.outputs.version_tag}}
      version_number: ${{needs.tag_release.outputs.version_tag}}
      commit_id: ${{ needs.get_commit_id.outputs.commit_id }}
      lambda_insights_log_group_name: /aws/lambda-insights
      deploy_artillery: true
      deploy_drift_detection: true
      is_pull_request: false
    secrets:
      cf_create_changeset_role: ${{ secrets.DEV_CLOUD_FORMATION_CREATE_CHANGESET_ROLE }}
      cf_deploy_role: ${{ secrets.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}

  deploy_ref_stacks:
    needs:
      [
        get_commit_id,
        package_code,
        package_cdk_code,
        tag_release,
        deploy_dev_stacks,
        get_config_values,
      ]
    uses: ./.github/workflows/release_all_stacks.yml
    permissions:
      id-token: write
      contents: write
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      target_environment: ref
      version: ${{ needs.tag_release.outputs.version_tag }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      execute_change_set: true
      lambda_stack_suffix: ""
      artifact_bucket_prefix: ${{needs.tag_release.outputs.version_tag}}
      version_number: ${{needs.tag_release.outputs.version_tag}}
      commit_id: ${{ needs.get_commit_id.outputs.commit_id }}
      lambda_insights_log_group_name: /aws/lambda-insights
      deploy_artillery: true
      deploy_drift_detection: true
      is_pull_request: false
    secrets:
      cf_create_changeset_role: ${{ secrets.REF_CLOUD_FORMATION_CREATE_CHANGESET_ROLE }}
      cf_deploy_role: ${{ secrets.REF_CLOUD_FORMATION_DEPLOY_ROLE }}

  deploy_qa_stacks:
    needs:
      [
        get_commit_id,
        package_code,
        package_cdk_code,
        tag_release,
        deploy_dev_stacks,
        get_config_values,
      ]
    uses: ./.github/workflows/release_all_stacks.yml
    permissions:
      id-token: write
      contents: write
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      target_environment: qa
      version: ${{ needs.tag_release.outputs.version_tag }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      execute_change_set: true
      lambda_stack_suffix: ""
      artifact_bucket_prefix: ${{needs.tag_release.outputs.version_tag}}
      version_number: ${{needs.tag_release.outputs.version_tag}}
      commit_id: ${{ needs.get_commit_id.outputs.commit_id }}
      lambda_insights_log_group_name: /aws/lambda-insights
      deploy_artillery: false
      deploy_drift_detection: true
      is_pull_request: false
    secrets:
      cf_create_changeset_role: ${{ secrets.QA_CLOUD_FORMATION_CREATE_CHANGESET_ROLE }}
      cf_deploy_role: ${{ secrets.QA_CLOUD_FORMATION_DEPLOY_ROLE }}
  deploy_int_stacks:
    needs:
      [
        get_commit_id,
        package_code,
        package_cdk_code,
        tag_release,
        get_config_values,
        deploy_qa_stacks,
      ]
    uses: ./.github/workflows/release_all_stacks.yml
    permissions:
      id-token: write
      contents: write
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      target_environment: int
      version: ${{ needs.tag_release.outputs.version_tag }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      execute_change_set: true
      lambda_stack_suffix: ""
      artifact_bucket_prefix: ${{needs.tag_release.outputs.version_tag}}
      version_number: ${{needs.tag_release.outputs.version_tag}}
      commit_id: ${{ needs.get_commit_id.outputs.commit_id }}
      lambda_insights_log_group_name: /aws/lambda-insights
      deploy_artillery: false
      deploy_drift_detection: true
      is_pull_request: false
    secrets:
      cf_create_changeset_role: ${{ secrets.INT_CLOUD_FORMATION_CREATE_CHANGESET_ROLE }}
      cf_deploy_role: ${{ secrets.INT_CLOUD_FORMATION_DEPLOY_ROLE }}

  deploy_prod_stacks:
    needs:
      [
        get_commit_id,
        package_code,
        package_cdk_code,
        tag_release,
        deploy_int_stacks,
        get_config_values,
      ]
    uses: ./.github/workflows/release_all_stacks.yml
    permissions:
      id-token: write
      contents: write

    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      target_environment: prod
      version: ${{ needs.tag_release.outputs.version_tag }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      execute_change_set: true
      lambda_stack_suffix: ""
      artifact_bucket_prefix: ${{needs.tag_release.outputs.version_tag}}
      version_number: ${{needs.tag_release.outputs.version_tag}}
      commit_id: ${{ needs.get_commit_id.outputs.commit_id }}
      lambda_insights_log_group_name: /aws/lambda-insights
      deploy_artillery: false
      deploy_drift_detection: true
      is_pull_request: false
    secrets:
      cf_create_changeset_role: ${{ secrets.PROD_CLOUD_FORMATION_CREATE_CHANGESET_ROLE }}
      cf_deploy_role: ${{ secrets.PROD_CLOUD_FORMATION_DEPLOY_ROLE }}
